SET IDENTITY_INSERT companies ON;

INSERT INTO companies (companyID, symbol, companyName, sector, subSector, city, companyState, cikCode)
 VALUES
    (1, 'A', 'Agilent Technologies Inc', 'Health Care', 'Health Care Equipment', 'Santa Clara', ' California', 1090872),
    (2, 'AAL', 'American Airlines Group', 'Industrials', 'Airlines', 'Fort Worth', ' Texas', 6201),
    (3, 'AAP', 'Advance Auto Parts', 'Consumer Discretionary', 'Automotive Retail', 'Roanoke', ' Virginia', 1158449),
    (4, 'AAPL', 'Apple Inc.', 'Information Technology', 'Computer Hardware', 'Cupertino', ' California', 320193),
    (5, 'ABBV', 'AbbVie', 'Health Care', 'Pharmaceuticals', 'North Chicago', ' Illinois', 1551152),
    (6, 'ABC', 'AmerisourceBergen Corp', 'Health Care', 'Health Care Distributors', 'Chesterbrook', ' Pennsylvania', 1140859),
    (7, 'ABT', 'Abbott Laboratories', 'Health Care', 'Health Care Equipment', 'North Chicago', ' Illinois', 1800),
    (8, 'ACN', 'Accenture plc', 'Information Technology', 'IT Consulting & Other Services', 'Dublin', ' Ireland', 1467373),
    (9, 'ADBE', 'Adobe Systems Inc', 'Information Technology', 'Application Software', 'San Jose', ' California', 796343),
    (10, 'ADI', 'Analog Devices, Inc.', 'Information Technology', 'Semiconductors', 'Norwood', ' Massachusetts', 6281),
    (11, 'ADM', 'Archer-Daniels-Midland Co', 'Consumer Staples', 'Agricultural Products', 'Decatur', ' Illinois', 7084),
    (12, 'ADP', 'Automatic Data Processing', 'Information Technology', 'Internet Software & Services', 'Roseland', ' New Jersey', 8670),
    (13, 'ADS', 'Alliance Data Systems', 'Information Technology', 'Data Processing & Outsourced Services', 'Plano', ' Texas', 1101215),
    (14, 'ADSK', 'Autodesk Inc', 'Information Technology', 'Application Software', 'San Rafael', ' California', 769397),
    (15, 'AEE', 'Ameren Corp', 'Utilities', 'MultiUtilities', 'St. Louis', ' Missouri', 1002910),
    (16, 'AEP', 'American Electric Power', 'Utilities', 'Electric Utilities', 'Columbus', ' Ohio', 4904),
    (17, 'AES', 'AES Corp', 'Utilities', 'Independent Power Producers & Energy Traders', 'Arlington', ' Virginia', 874761),
    (18, 'AET', 'Aetna Inc', 'Health Care', 'Managed Health Care', 'Hartford', ' Connecticut', 1122304),
    (19, 'AFL', 'AFLAC Inc', 'Financials', 'Life & Health Insurance', 'Columbus', ' Georgia', 4977),
    (20, 'AGN', 'Allergan, Plc', 'Health Care', 'Pharmaceuticals', 'Dublin', ' Ireland', 884629),
    (21, 'AIG', 'American International Group, Inc.', 'Financials', 'Property & Casualty Insurance', 'New York', ' New York', 5272),
    (22, 'AIV', 'Apartment Investment & Mgmt', 'Real Estate', 'REITs', 'Denver', ' Colorado', 922864),
    (23, 'AIZ', 'Assurant Inc', 'Financials', 'Multi-line Insurance', 'New York', ' New York', 1267238),
    (24, 'AJG', 'Arthur J. Gallagher & Co.', 'Financials', 'Insurance Brokers', 'Itasca', ' Illinois', 354190),
    (25, 'AKAM', 'Akamai Technologies Inc', 'Information Technology', 'Internet Software & Services', 'Cambridge', ' Massachusetts', 1086222),
    (26, 'ALB', 'Albemarle Corp', 'Materials', 'Specialty Chemicals', 'Baton Rouge', ' Louisiana', 915913),
    (27, 'ALK', 'Alaska Air Group Inc', 'Industrials', 'Airlines', 'Seattle', ' Washington', 766421),
    (28, 'ALL', 'Allstate Corp', 'Financials', 'Property & Casualty Insurance', 'Northfield Township', ' Illinois', 899051),
    (29, 'ALLE', 'Allegion', 'Industrials', 'Building Products', 'Dublin', ' Ireland', 1579241),
    (30, 'ALXN', 'Alexion Pharmaceuticals', 'Health Care', 'Biotechnology', 'Cheshire', ' Connecticut', 899866),
    (31, 'AMAT', 'Applied Materials Inc', 'Information Technology', 'Semiconductor Equipment', 'Santa Clara', ' California', 6951),
    (32, 'AME', 'AMETEK Inc', 'Industrials', 'Electrical Components & Equipment', 'Berwyn', ' Pennsylvania', 1037868),
    (33, 'AMG', 'Affiliated Managers Group Inc', 'Financials', 'Asset Management & Custody Banks', 'Beverly', ' Massachusetts', 1004434),
    (34, 'AMGN', 'Amgen Inc', 'Health Care', 'Biotechnology', 'Thousand Oaks', ' California', 318154),
    (35, 'AMP', 'Ameriprise Financial', 'Financials', 'Asset Management & Custody Banks', 'Minneapolis', ' Minnesota', 820027),
    (36, 'AMT', 'American Tower Corp A', 'Real Estate', 'Specialized REITs', 'Boston', ' Massachusetts', 1053507),
    (37, 'AMZN', 'Amazon.com Inc', 'Consumer Discretionary', 'Internet & Direct Marketing Retail', 'Seattle', ' Washington', 1018724),
    (38, 'AN', 'AutoNation Inc', 'Consumer Discretionary', 'Specialty Stores', 'Fort Lauderdale', ' Florida', 350698),
    (39, 'ANTM', 'Anthem Inc.', 'Health Care', 'Managed Health Care', 'Indianapolis', ' Indiana', 1156039),
    (40, 'AON', 'Aon plc', 'Financials', 'Insurance Brokers', 'London', ' United Kingdom', 315293),
    (41, 'APA', 'Apache Corporation', 'Energy', 'Oil & Gas Exploration & Production', 'Houston', ' Texas', 6769),
    (42, 'APC', 'Anadarko Petroleum Corp', 'Energy', 'Oil & Gas Exploration & Production', 'The Woodlands', ' Texas', 773910),
    (43, 'APD', 'Air Products & Chemicals Inc', 'Materials', 'Industrial Gases', 'Allentown', ' Pennsylvania', 2969),
    (44, 'APH', 'Amphenol Corp', 'Information Technology', 'Electronic Components', 'Wallingford', ' Connecticut', 820313),
    (45, 'ARNC', 'Arconic Inc', 'Industrials', 'Aerospace & Defense', 'New York', ' New York', 4281),
    (46, 'ATVI', 'Activision Blizzard', 'Information Technology', 'Home Entertainment Software', 'Santa Monica', ' California', 718877),
    (47, 'AVB', 'AvalonBay Communities, Inc.', 'Real Estate', 'Residential REITs', 'Arlington', ' Virginia', 915912),
    (48, 'AVGO', 'Broadcom', 'Information Technology', 'Semiconductors', 'San Jose', ' California', 1441634),
    (49, 'AVY', 'Avery Dennison Corp', 'Materials', 'Paper Packaging', 'Glendale', ' California', 8818),
    (50, 'AWK', 'American Water Works Company Inc', 'Utilities', 'Water Utilities', 'Voorhees', ' New Jersey', 1410636),
    (51, 'AXP', 'American Express Co', 'Financials', 'Consumer Finance', 'New York', ' New York', 4962),
    (52, 'AYI', 'Acuity Brands Inc', 'Industrials', 'Electrical Components & Equipment', 'Atlanta', ' Georgia', 1144215),
    (53, 'AZO', 'AutoZone Inc', 'Consumer Discretionary', 'Specialty Stores', 'Memphis', ' Tennessee', 866787),
    (54, 'BA', 'Boeing Company', 'Industrials', 'Aerospace & Defense', 'Chicago', ' Illinois', 12927),
    (55, 'BAC', 'Bank of America Corp', 'Financials', 'Banks', 'Charlotte', ' North Carolina', 70858),
    (56, 'BAX', 'Baxter International Inc.', 'Health Care', 'Health Care Equipment', 'Deerfield', ' Illinois', 10456),
    (57, 'BBBY', 'Bed Bath & Beyond', 'Consumer Discretionary', 'Specialty Stores', 'Union', ' New Jersey', 886158),
    (58, 'BBT', 'BB&T Corporation', 'Financials', 'Banks', 'Winston-Salem', ' North Carolina', 92230),
    (59, 'BBY', 'Best Buy Co. Inc.', 'Consumer Discretionary', 'Computer & Electronics Retail', 'Richfield', ' Minnesota', 764478),
    (60, 'BCR', 'Bard (C.R.) Inc.', 'Health Care', 'Health Care Equipment', 'Murray Hill', ' New Jersey', 9892),
    (61, 'BDX', 'Becton Dickinson', 'Health Care', 'Health Care Equipment', 'Franklin Lakes', ' New Jersey', 10795),
    (62, 'BEN', 'Franklin Resources', 'Financials', 'Asset Management & Custody Banks', 'San Mateo', ' California', 38777),
    (63, 'BF.B', 'Brown-Forman Corporation', 'Consumer Staples', 'Distillers & Vintners', 'Louisville', ' Kentucky', 14693),
    (64, 'BHI', 'Baker Hughes Inc', 'Energy', 'Oil & Gas Equipment & Services', 'Houston', ' Texas', 808362),
    (65, 'BIIB', 'BIOGEN IDEC Inc.', 'Health Care', 'Biotechnology', 'Weston', ' Massachusetts', 875045),
    (66, 'BK', 'The Bank of New York Mellon Corp.', 'Financials', 'Banks', 'New York', ' New York', 1390777),
    (67, 'BLK', 'BlackRock', 'Financials', 'Asset Management & Custody Banks', 'New York', ' New York', 1364742),
    (68, 'BLL', 'Ball Corp', 'Materials', 'Metal & Glass Containers', 'Broomfield', ' Colorado', 9389),
    (69, 'BMY', 'Bristol-Myers Squibb', 'Health Care', 'Health Care Distributors', 'New York', ' New York', 14272),
    (70, 'BRK.B', 'Berkshire Hathaway', 'Financials', 'Multi-Sector Holdings', 'Omaha', ' Nebraska', 1067983),
    (71, 'BSX', 'Boston Scientific', 'Health Care', 'Health Care Equipment', 'Marlborough', ' Massachusetts', 885725),
    (72, 'BWA', 'BorgWarner', 'Consumer Discretionary', 'Auto Parts & Equipment', 'Auburn Hills', ' Michigan', 908255),
    (73, 'BXP', 'Boston Properties', 'Real Estate', 'REITs', 'Boston', ' Massachusetts', 1037540),
    (74, 'C', 'Citigroup Inc.', 'Financials', 'Banks', 'New York', ' New York', 831001),
    (75, 'CA', 'CA, Inc.', 'Information Technology', 'Systems Software', 'Islandia', ' New York', 356028),
    (76, 'CAG', 'ConAgra Foods Inc.', 'Consumer Staples', 'Packaged Foods & Meats', 'Omaha', ' Nebraska', 23217),
    (77, 'CAH', 'Cardinal Health Inc.', 'Health Care', 'Health Care Distributors', 'Dublin', ' Ohio', 721371),
    (78, 'CAT', 'Caterpillar Inc.', 'Industrials', 'Construction & Farm Machinery & Heavy Trucks', 'Peoria', ' Illinois', 18230),
    (79, 'CB', 'Chubb Limited', 'Financials', 'Property & Casualty Insurance', 'Zurich', ' Switzerland', 896159),
    (80, 'CBG', 'CBRE Group', 'Real Estate', 'Real Estate Services', 'Los Angeles', ' California', 1138118),
    (81, 'CBS', 'CBS Corp.', 'Consumer Discretionary', 'Broadcasting & Cable TV', 'New York', ' New York', 813828),
    (82, 'CCI', 'Crown Castle International Corp.', 'Real Estate', 'REITs', 'Houston', ' Texas', 1051470),
    (83, 'CCL', 'Carnival Corp.', 'Consumer Discretionary', 'Hotels, Resorts & Cruise Lines', 'Miami', ' Florida', 815097),
    (84, 'CELG', 'Celgene Corp.', 'Health Care', 'Biotechnology', 'Summit', ' New Jersey', 816284),
    (85, 'CERN', 'Cerner', 'Health Care', 'Health Care Technology', 'North Kansas City', ' Missouri', 804753),
    (86, 'CF', 'CF Industries Holdings Inc', 'Materials', 'Fertilizers & Agricultural Chemicals', 'Deerfield', ' Illinois', 1324404),
    (87, 'CFG', 'Citizens Financial Group', 'Financials', 'Regional Banks', 'Providence', ' Rhode Island', 759944),
    (88, 'CHD', 'Church & Dwight', 'Consumer Staples', 'Household Products', 'Ewing', ' New Jersey', 313927),
    (89, 'CHK', 'Chesapeake Energy', 'Energy', 'Integrated Oil & Gas', 'Oklahoma City', ' Oklahoma', 895126),
    (90, 'CHRW', 'C. H. Robinson Worldwide', 'Industrials', 'Air Freight & Logistics', 'Eden Prairie', ' Minnesota', 1043277),
    (91, 'CHTR', 'Charter Communications', 'Consumer Discretionary', 'Cable & Satellite', 'Stamford', ' Connecticut', 1091667),
    (92, 'CI', 'CIGNA Corp.', 'Health Care', 'Managed Health Care', 'Philadelphia', ' Pennsylvania', 701221),
    (93, 'CINF', 'Cincinnati Financial', 'Financials', 'Property & Casualty Insurance', 'Fairfield', ' Ohio', 20286),
    (94, 'CL', 'Colgate-Palmolive', 'Consumer Staples', 'Household Products', 'New York', ' New York', 21665),
    (95, 'CLX', 'The Clorox Company', 'Consumer Staples', 'Household Products', 'Oakland', ' California', 21076),
    (96, 'CMA', 'Comerica Inc.', 'Financials', 'Regional Banks', 'Dallas', ' Texas', 28412),
    (97, 'CMCSA', 'Comcast A Corp', 'Consumer Discretionary', 'Cable & Satellite', 'Philadelphia', ' Pennsylvania', 1166691),
    (98, 'CME', 'CME Group Inc.', 'Financials', 'Financial Exchanges & Data', 'Chicago', ' Illinois', 1156375),
    (99, 'CMG', 'Chipotle Mexican Grill', 'Consumer Discretionary', 'Restaurants', 'Denver', ' Colorado', 1058090),
    (100, 'CMI', 'Cummins Inc.', 'Industrials', 'Industrial Machinery', 'Columbus', ' Indiana', 26172),
    (101, 'CMS', 'CMS Energy', 'Utilities', 'MultiUtilities', 'Jackson', ' Michigan', 811156),
    (102, 'CNC', 'Centene Corporation', 'Health Care', 'Managed Health Care', 'St Louis', ' Missouri', 1071739),
    (103, 'CNP', 'CenterPoint Energy', 'Utilities', 'MultiUtilities', 'Houston', ' Texas', 1130310),
    (104, 'COF', 'Capital One Financial', 'Financials', 'Consumer Finance', 'Tysons Corner', ' Virginia', 927628),
    (105, 'COG', 'Cabot Oil & Gas', 'Energy', 'Oil & Gas Exploration & Production', 'Houston', ' Texas', 858470),
    (106, 'COH', 'Coach Inc.', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'New York', ' New York', 1116132),
    (107, 'COL', 'Rockwell Collins', 'Industrials', 'Industrial Conglomerates', 'Cedar Rapids', ' Iowa', 1137411),
    (108, 'COO', 'The Cooper Companies', 'Health Care', 'Health Care Supplies', 'Pleasanton', ' California', 711404),
    (109, 'COP', 'ConocoPhillips', 'Energy', 'Oil & Gas Exploration & Production', 'Houston', ' Texas', 1163165),
    (110, 'COST', 'Costco Co.', 'Consumer Staples', 'Hypermarkets & Super Centers', 'Issaquah', ' Washington', 909832),
    (111, 'COTY', 'Coty, Inc', 'Consumer Staples', 'Personal Products', 'New York', ' NY', 1024305),
    (112, 'CPB', 'Campbell Soup', 'Consumer Staples', 'Packaged Foods & Meats', 'Camden', ' New Jersey', 16732),
    (113, 'CRM', 'Salesforce.com', 'Information Technology', 'Internet Software & Services', 'San Francisco', ' California', 1108524),
    (114, 'CSCO', 'Cisco Systems', 'Information Technology', 'Networking Equipment', 'San Jose', ' California', 858877),
    (115, 'CSRA', 'CSRA Inc.', 'Information Technology', 'IT Consulting & Other Services', 'Falls Church', ' Virginia', 1646383),
    (116, 'CSX', 'CSX Corp.', 'Industrials', 'Railroads', 'Jacksonville', ' Florida', 277948),
    (117, 'CTAS', 'Cintas Corporation', 'Industrials', 'Diversified Support Services', 'Mason', ' Ohio', 723254),
    (118, 'CTL', 'CenturyLink Inc', 'Telecommunications Services', 'Integrated Telecommunications Services', 'Monroe', ' Louisiana', 18926),
    (119, 'CTSH', 'Cognizant Technology Solutions', 'Information Technology', 'IT Consulting & Other Services', 'Teaneck', ' New Jersey', 1058290),
    (120, 'CTXS', 'Citrix Systems', 'Information Technology', 'Internet Software & Services', 'Fort Lauderdale', ' Florida', 877890),
    (121, 'CVS', 'CVS Health', 'Consumer Staples', 'Drug Retail', 'Woonsocket', ' Rhode Island', 64803),
    (122, 'CVX', 'Chevron Corp.', 'Energy', 'Integrated Oil & Gas', 'San Ramon', ' California', 93410),
    (123, 'CXO', 'Concho Resources', 'Energy', 'Oil & Gas Exploration & Production', 'Midland', ' Texas', 1358071),
    (124, 'D', 'Dominion Resources', 'Utilities', 'Electric Utilities', 'Richmond', ' Virginia', 715957),
    (125, 'DAL', 'Delta Air Lines', 'Industrials', 'Airlines', 'Atlanta', ' Georgia', 27904),
    (126, 'DD', 'Du Pont (E.I.)', 'Materials', 'Diversified Chemicals', 'Wilmington', ' Delaware', 30554),
    (127, 'DE', 'Deere & Co.', 'Industrials', 'Construction & Farm Machinery & Heavy Trucks', 'Moline', ' Illinois', 315189),
    (128, 'DFS', 'Discover Financial Services', 'Financials', 'Consumer Finance', 'Riverwoods', ' Illinois', 1393612),
    (129, 'DG', 'Dollar General', 'Consumer Discretionary', 'General Merchandise Stores', 'Goodlettsville', ' Tennessee', 29534),
    (130, 'DGX', 'Quest Diagnostics', 'Health Care', 'Health Care Facilities', 'Madison', ' New Jersey', 1022079),
    (131, 'DHI', 'D. R. Horton', 'Consumer Discretionary', 'Homebuilding', 'Fort Worth', ' Texas', 882184),
    (132, 'DHR', 'Danaher Corp.', 'Industrials', 'Industrial Conglomerates', 'Washington', ' D.C.', 313616),
    (133, 'DIS', 'The Walt Disney Company', 'Consumer Discretionary', 'Broadcasting & Cable TV', 'Burbank', ' California', 1001039),
    (134, 'DISCA', 'Discovery Communications-A', 'Consumer Discretionary', 'Cable & Satellite', 'Silver Spring', ' Maryland', 1437107),
    (135, 'DISCK', 'Discovery Communications-C', 'Consumer Discretionary', 'Cable & Satellite', 'Silver Spring', ' Maryland', 1437107),
    (136, 'DLPH', 'Delphi Automotive', 'Consumer Discretionary', 'Auto Parts & Equipment', 'Gillingham', ' Kent', 1521332),
    (137, 'DLR', 'Digital Realty Trust', 'Real Estate', 'Specialized REITs', 'San Francisco', ' California', 1297996),
    (138, 'DLTR', 'Dollar Tree', 'Consumer Discretionary', 'General Merchandise Stores', 'Chesapeake', ' Virginia', 935703),
    (139, 'DNB', 'Dun & Bradstreet', 'Industrials', 'Research & Consulting Services', 'Short Hills', ' New Jersey', 1115222),
    (140, 'DOV', 'Dover Corp.', 'Industrials', 'Industrial Machinery', 'Downers Grove', ' Illinois', 29905),
    (141, 'DOW', 'Dow Chemical', 'Materials', 'Diversified Chemicals', 'Midland', ' Michigan', 29915),
    (142, 'DPS', 'Dr Pepper Snapple Group', 'Consumer Staples', 'Soft Drinks', 'Plano', ' Texas', 1418135),
    (143, 'DRI', 'Darden Restaurants', 'Consumer Discretionary', 'Restaurants', 'Orlando', ' Florida', 940944),
    (144, 'DTE', 'DTE Energy Co.', 'Utilities', 'MultiUtilities', 'Detroit', ' Michigan', 936340),
    (145, 'DUK', 'Duke Energy', 'Utilities', 'Electric Utilities', 'Charlotte', ' North Carolina', 1326160),
    (146, 'DVA', 'DaVita Inc.', 'Health Care', 'Health Care Facilities', 'Denver', ' Colorado', 927066),
    (147, 'DVN', 'Devon Energy Corp.', 'Energy', 'Oil & Gas Exploration & Production', 'Oklahoma City', ' Oklahoma', 1090012),
    (148, 'EA', 'Electronic Arts', 'Information Technology', 'Home Entertainment Software', 'Redwood City', ' California', 712515),
    (149, 'EBAY', 'eBay Inc.', 'Information Technology', 'Internet Software & Services', 'San Jose', ' California', 1065088),
    (150, 'ECL', 'Ecolab Inc.', 'Materials', 'Specialty Chemicals', 'St. Paul', ' Minnesota', 31462),
    (151, 'ED', 'Consolidated Edison', 'Utilities', 'Electric Utilities', 'New York', ' New York', 1047862),
    (152, 'EFX', 'Equifax Inc.', 'Industrials', 'Research & Consulting Services', 'Atlanta', ' Georgia', 33185),
    (153, 'EIX', 'Edison Int''l', 'Utilities', 'Electric Utilities', 'Rosemead', ' California', 827052),
    (154, 'EL', 'Estee Lauder Cos.', 'Consumer Staples', 'Personal Products', 'New York', ' New York', 1001250),
    (155, 'EMN', 'Eastman Chemical', 'Materials', 'Diversified Chemicals', 'Kingsport', ' Tennessee', 915389),
    (156, 'EMR', 'Emerson Electric Company', 'Industrials', 'Industrial Conglomerates', 'Ferguson', ' Missouri', 32604),
    (157, 'ENDP', 'Endo International', 'Health Care', 'Pharmaceuticals', 'Dublin', ' Ireland', 1100962),
    (158, 'EOG', 'EOG Resources', 'Energy', 'Oil & Gas Exploration & Production', 'Houston', ' Texas', 821189),
    (159, 'EQIX', 'Equinix', 'Real Estate', 'REITs', 'Redwood City', ' California', 1101239),
    (160, 'EQR', 'Equity Residential', 'Real Estate', 'REITs', 'Chicago', ' Illinois', 906107),
    (161, 'EQT', 'EQT Corporation', 'Energy', 'Oil & Gas Exploration & Production', 'Pittsburgh', ' Pennsylvania', 33213),
    (162, 'ES', 'Eversource Energy', 'Utilities', 'MultiUtilities', 'Springfield', ' Massachusetts', 72741),
    (163, 'ESRX', 'Express Scripts', 'Health Care', 'Health Care Distributors', 'Cool Valley', ' Missouri', 1532063),
    (164, 'ESS', 'Essex Property Trust, Inc.', 'Real Estate', 'Residential REITs', 'Palo Alto', ' California', 920522),
    (165, 'ETFC', 'E*Trade', 'Financials', 'Investment Banking & Brokerage', 'New York', ' New York', 1015780),
    (166, 'ETN', 'Eaton Corporation', 'Industrials', 'Industrial Conglomerates', 'Dublin', ' Ireland', 1551182),
    (167, 'ETR', 'Entergy Corp.', 'Utilities', 'Electric Utilities', 'New Orleans', ' Louisiana', 65984),
    (168, 'EVHC', 'Envision Healthcare Corp', 'Health Care', 'Health Care Services', 'Nashville', ' Tennessee', 895930),
    (169, 'EW', 'Edwards Lifesciences', 'Health Care', 'Health Care Equipment', 'Irvine', ' California', 1099800),
    (170, 'EXC', 'Exelon Corp.', 'Utilities', 'MultiUtilities', 'Chicago', ' Illinois', 1109357),
    (171, 'EXPD', 'Expeditors Int''l', 'Industrials', 'Air Freight & Logistics', 'Seattle', ' Washington', 746515),
    (172, 'EXPE', 'Expedia Inc.', 'Consumer Discretionary', 'Internet & Direct Marketing Retail', 'Bellevue', ' Washington', 1324424),
    (173, 'EXR', 'Extra Space Storage', 'Real Estate', 'Specialized REITs', 'Salt Lake City', ' UT', 1289490),
    (174, 'F', 'Ford Motor', 'Consumer Discretionary', 'Automobile Manufacturers', 'Dearborn', ' Michigan', 37996),
    (175, 'FAST', 'Fastenal Co', 'Industrials', 'Building Products', 'Winona', ' Minnesota', 815556),
    (176, 'FB', 'Facebook', 'Information Technology', 'Internet Software & Services', 'Menlo Park', ' California', 1326801),
    (177, 'FBHS', 'Fortune Brands Home & Security', 'Industrials', 'Building Products', 'Deerfield', ' Illinois', 1519751),
    (178, 'FCX', 'Freeport-McMoran Cp & Gld', 'Materials', 'Copper', 'Phoenix', ' Arizona', 831259),
    (179, 'FDX', 'FedEx Corporation', 'Industrials', 'Air Freight & Logistics', 'Memphis', ' Tennessee', 1048911),
    (180, 'FE', 'FirstEnergy Corp', 'Utilities', 'Electric Utilities', 'Akron', ' Ohio', 1031296),
    (181, 'FFIV', 'F5 Networks', 'Information Technology', 'Networking Equipment', 'Seattle', ' Washington', 1048695),
    (182, 'FIS', 'Fidelity National Information Services', 'Information Technology', 'Internet Software & Services', 'Jacksonville', ' Florida', 1136893),
    (183, 'FISV', 'Fiserv Inc', 'Information Technology', 'Internet Software & Services', 'Brookfield', ' Wisconsin', 798354),
    (184, 'FITB', 'Fifth Third Bancorp', 'Financials', 'Banks', 'Cincinnati', ' Ohio', 35527),
    (185, 'FL', 'Foot Locker Inc', 'Consumer Discretionary', 'Apparel Retail', 'New York', ' New York', 850209),
    (186, 'FLIR', 'FLIR Systems', 'Information Technology', 'Electronic Equipment & Instruments', 'Wilsonville', ' Oregon', 354908),
    (187, 'FLR', 'Fluor Corp.', 'Industrials', 'Diversified Commercial Services', 'Irving', ' Texas', 1124198),
    (188, 'FLS', 'Flowserve Corporation', 'Industrials', 'Industrial Machinery', 'Irving', ' Texas', 30625),
    (189, 'FMC', 'FMC Corporation', 'Materials', 'Diversified Chemicals', 'Philadelphia', ' Pennsylvania', 37785),
    (190, 'FOX', 'Twenty-First Century Fox Class B', 'Consumer Discretionary', 'Publishing', 'New York', ' New York', 1308161),
    (191, 'FOXA', 'Twenty-First Century Fox Class A', 'Consumer Discretionary', 'Publishing', 'New York', ' New York', 1308161),
    (192, 'FRT', 'Federal Realty Investment Trust', 'Real Estate', 'Retail REITs', 'Rockville', ' Maryland', 34903),
    (193, 'FSLR', 'First Solar Inc', 'Information Technology', 'Semiconductors', 'Tempe', ' Arizona', 1274494),
    (194, 'FTI', 'FMC Technologies Inc.', 'Energy', 'Oil & Gas Equipment & Services', 'Houston', ' Texas', 1135152),
    (195, 'FTR', 'Frontier Communications', 'Telecommunications Services', 'Integrated Telecommunications Services', 'Stamford', ' Connecticut', 20520),
    (196, 'FTV', 'Fortive Corp', 'Industrials', 'Industrial Machinery', 'Everett', ' Washington', 1659166),
    (197, 'GD', 'General Dynamics', 'Industrials', 'Aerospace & Defense', 'Falls Church', ' Virginia', 40533),
    (198, 'GE', 'General Electric', 'Industrials', 'Industrial Conglomerates', 'Fairfield', ' Connecticut', 40545),
    (199, 'GGP', 'General Growth Properties Inc.', 'Real Estate', 'Retail REITs', 'Chicago', ' Illinois', 895648),
    (200, 'GILD', 'Gilead Sciences', 'Health Care', 'Biotechnology', 'Foster City', ' California', 882095),
    (201, 'GIS', 'General Mills', 'Consumer Staples', 'Packaged Foods & Meats', 'Golden Valley', ' Minnesota', 40704),
    (202, 'GLW', 'Corning Inc.', 'Information Technology', 'Electronic Components', 'Corning', ' New York', 24741),
    (203, 'GM', 'General Motors', 'Consumer Discretionary', 'Automobile Manufacturers', 'Detroit', ' Michigan', 1467858),
    (204, 'GOOG', 'Alphabet Inc Class C', 'Information Technology', 'Internet Software & Services', 'Mountain View', ' California', 1652044),
    (205, 'GOOGL', 'Alphabet Inc Class A', 'Information Technology', 'Internet Software & Services', 'Mountain View', ' California', 1652044),
    (206, 'GPC', 'Genuine Parts', 'Consumer Discretionary', 'Specialty Stores', 'Atlanta', ' Georgia', 40987),
    (207, 'GPN', 'Global Payments Inc', 'Information Technology', 'Data Processing & Outsourced Services', 'Atlanta', ' Georgia', 1123360),
    (208, 'GPS', 'Gap (The)', 'Consumer Discretionary', 'Apparel Retail', 'San Francisco', ' California', 39911),
    (209, 'GRMN', 'Garmin Ltd.', 'Consumer Discretionary', 'Consumer Electronics', 'Schaffhausen', ' Switzerland', 1121788),
    (210, 'GS', 'Goldman Sachs Group', 'Financials', 'Investment Banking & Brokerage', 'New York', ' New York', 886982),
    (211, 'GT', 'Goodyear Tire & Rubber', 'Consumer Discretionary', 'Tires & Rubber', 'Akron', ' Ohio', 42582),
    (212, 'GWW', 'Grainger (W.W.) Inc.', 'Industrials', 'Industrial Materials', 'Lake Forest', ' Illinois', 277135),
    (213, 'HAL', 'Halliburton Co.', 'Energy', 'Oil & Gas Equipment & Services', 'Houston', ' Texas', 45012),
    (214, 'HAR', 'Harman Int''l Industries', 'Consumer Discretionary', 'Consumer Electronics', 'Stamford', ' Connecticut', 800459),
    (215, 'HAS', 'Hasbro Inc.', 'Consumer Discretionary', 'Leisure Products', 'Pawtucket', ' Rhode Island', 46080),
    (216, 'HBAN', 'Huntington Bancshares', 'Financials', 'Banks', 'Columbus', ' Ohio', 49196),
    (217, 'HBI', 'Hanesbrands Inc', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'Winston-Salem', ' North Carolina', 1359841),
    (218, 'HCA', 'HCA Holdings', 'Health Care', 'Health Care Facilities', 'Nashville', ' Tennessee', 860730),
    (219, 'HCN', 'Welltower Inc.', 'Real Estate', 'REITs', 'Toledo', ' Ohio', 766704),
    (220, 'HCP', 'HCP Inc.', 'Real Estate', 'REITs', 'Long Beach', ' California', 765880),
    (221, 'HD', 'Home Depot', 'Consumer Discretionary', 'Home Improvement Retail', 'Atlanta', ' Georgia', 354950),
    (222, 'HES', 'Hess Corporation', 'Energy', 'Integrated Oil & Gas', 'New York', ' New York', 4447),
    (223, 'HIG', 'Hartford Financial Svc.Gp.', 'Financials', 'Property & Casualty Insurance', 'Hartford', ' Connecticut', 874766),
    (224, 'HOG', 'Harley-Davidson', 'Consumer Discretionary', 'Motorcycle Manufacturers', 'Milwaukee', ' Wisconsin', 793952),
    (225, 'HOLX', 'Hologic', 'Health Care', 'Health Care Equipment', 'Marlborough', ' Massachusetts', 859737),
    (226, 'HON', 'Honeywell Int''l Inc.', 'Industrials', 'Industrial Conglomerates', 'Morristown', ' New Jersey', 773840),
    (227, 'HP', 'Helmerich & Payne', 'Energy', 'Oil & Gas Drilling', 'Tulsa', ' Oklahoma', 46765),
    (228, 'HPE', 'Hewlett Packard Enterprise', 'Information Technology', 'Technology Hardware, Storage & Peripherals', 'Palo Alto', ' California', 1645590),
    (229, 'HPQ', 'HP Inc.', 'Information Technology', 'Computer Hardware', 'Palo Alto', ' California', 47217),
    (230, 'HRB', 'Block H&R', 'Financials', 'Consumer Finance', 'Kansas City', ' Missouri', 12659),
    (231, 'HRL', 'Hormel Foods Corp.', 'Consumer Staples', 'Packaged Foods & Meats', 'Austin', ' Minnesota', 48465),
    (232, 'HRS', 'Harris Corporation', 'Information Technology', 'Telecommunications Equipment', 'Melbourne', ' Florida', 202058),
    (233, 'HSIC', 'Henry Schein', 'Health Care', 'Health Care Distributors', 'Melville', ' New York', 1000228),
    (234, 'HST', 'Host Hotels & Resorts', 'Real Estate', 'REITs', 'Bethesda', ' Maryland', 1070750),
    (235, 'HSY', 'The Hershey Company', 'Consumer Staples', 'Packaged Foods & Meats', 'Hershey', ' Pennsylvania', 47111),
    (236, 'HUM', 'Humana Inc.', 'Health Care', 'Managed Health Care', 'Louisville', ' Kentucky', 49071),
    (237, 'IBM', 'International Business Machines', 'Information Technology', 'IT Consulting & Other Services', 'Armonk', ' New York', 51143),
    (238, 'ICE', 'Intercontinental Exchange', 'Financials', 'Diversified Financial Services', 'Atlanta', ' Georgia', 1571949),
    (239, 'IDXX', 'IDEXX Laboratories', 'Health Care', 'Health Care Equipment', 'Westbrook', ' Maine', 874716),
    (240, 'IFF', 'Intl Flavors & Fragrances', 'Materials', 'Specialty Chemicals', 'New York', ' New York', 51253),
    (241, 'ILMN', 'Illumina Inc', 'Health Care', 'Life Sciences Tools & Services', 'San Diego', ' California', 1110803),
    (242, 'INTC', 'Intel Corp.', 'Information Technology', 'Semiconductors', 'Santa Clara', ' California', 50863),
    (243, 'INTU', 'Intuit Inc.', 'Information Technology', 'Internet Software & Services', 'Mountain View', ' California', 896878),
    (244, 'IP', 'International Paper', 'Materials', 'Paper Packaging', 'Memphis', ' Tennessee', 51434),
    (245, 'IPG', 'Interpublic Group', 'Consumer Discretionary', 'Advertising', 'New York', ' New York', 51644),
    (246, 'IR', 'Ingersoll-Rand PLC', 'Industrials', 'Industrial Conglomerates', 'Dublin', ' Ireland', 1466258),
    (247, 'IRM', 'Iron Mountain Incorporated', 'Real Estate', 'REITs', 'Boston', ' Massachusetts', 1020569),
    (248, 'ISRG', 'Intuitive Surgical Inc.', 'Health Care', 'Health Care Equipment', 'Sunnyvale', ' California', 1035267),
    (249, 'ITW', 'Illinois Tool Works', 'Industrials', 'Industrial Machinery', 'Glenview', ' Illinois', 49826),
    (250, 'IVZ', 'Invesco Ltd.', 'Financials', 'Asset Management & Custody Banks', 'Atlanta', ' Georgia', 914208),
    (251, 'JBHT', 'J. B. Hunt Transport Services', 'Industrials', 'Trucking', 'Lowell', ' Arkansas', 728535),
    (252, 'JCI', 'Johnson Controls International', 'Industrials', 'Building Products', 'Cork', ' Ireland', 833444),
    (253, 'JEC', 'Jacobs Engineering Group', 'Industrials', 'Industrial Conglomerates', 'Pasadena', ' California', 52988),
    (254, 'JNJ', 'Johnson & Johnson', 'Health Care', 'Health Care Equipment', 'New Brunswick', ' New Jersey', 200406),
    (255, 'JNPR', 'Juniper Networks', 'Information Technology', 'Networking Equipment', 'Sunnyvale', ' California', 1043604),
    (256, 'JPM', 'JPMorgan Chase & Co.', 'Financials', 'Banks', 'New York', ' New York', 19617),
    (257, 'JWN', 'Nordstrom', 'Consumer Discretionary', 'Department Stores', 'Seattle', ' Washington', 72333),
    (258, 'K', 'Kellogg Co.', 'Consumer Staples', 'Packaged Foods & Meats', 'Battle Creek', ' Michigan', 55067),
    (259, 'KEY', 'KeyCorp', 'Financials', 'Banks', 'Cleveland', ' Ohio', 91576),
    (260, 'KHC', 'Kraft Heinz Co', 'Consumer Staples', 'Packaged Foods & Meats', 'Pittsburgh', ' Pennsylvania', 1545158),
    (261, 'KIM', 'Kimco Realty', 'Real Estate', 'REITs', 'New Hyde Park', ' New York', 879101),
    (262, 'KLAC', 'KLA-Tencor Corp.', 'Information Technology', 'Semiconductor Equipment', 'Milpitas', ' California', 319201),
    (263, 'KMB', 'Kimberly-Clark', 'Consumer Staples', 'Household Products', 'Irving', ' Texas', 55785),
    (264, 'KMI', 'Kinder Morgan', 'Energy', 'Oil & Gas Refining & Marketing & Transportation', 'Houston', ' Texas', 1506307),
    (265, 'KMX', 'Carmax Inc', 'Consumer Discretionary', 'Specialty Stores', 'Richmond', ' Virginia', 1170010),
    (266, 'KO', 'Coca Cola Company', 'Consumer Staples', 'Soft Drinks', 'Atlanta', ' Georgia', 21344),
    (267, 'KORS', 'Michael Kors Holdings', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'New York', ' New York', 1530721),
    (268, 'KR', 'Kroger Co.', 'Consumer Staples', 'Food Retail', 'Cincinnati', ' Ohio', 56873),
    (269, 'KSS', 'Kohl''s Corp.', 'Consumer Discretionary', 'General Merchandise Stores', 'Menomonee Falls', ' Wisconsin', 885639),
    (270, 'KSU', 'Kansas City Southern', 'Industrials', 'Railroads', 'Kansas City', ' Missouri', 54480),
    (271, 'L', 'Loews Corp.', 'Financials', 'Multi-Sector Holdings', 'New York', ' New York', 60086),
    (272, 'LB', 'L Brands Inc.', 'Consumer Discretionary', 'Apparel Retail', 'Columbus', ' Ohio', 701985),
    (273, 'LEG', 'Leggett & Platt', 'Industrials', 'Industrial Conglomerates', 'Carthage', ' Missouri', 58492),
    (274, 'LEN', 'Lennar Corp.', 'Consumer Discretionary', 'Homebuilding', 'Miami', ' Florida', 920760),
    (275, 'LH', 'Laboratory Corp. of America Holding', 'Health Care', 'Health Care Facilities', 'Burlington', ' North Carolina', 920148),
    (276, 'LKQ', 'LKQ Corporation', 'Consumer Discretionary', 'Distributors', 'Chicago', ' Illinois', 1065696),
    (277, 'LLL', 'L-3 Communications Holdings', 'Industrials', 'Industrial Conglomerates', 'New York', ' New York', 1056239),
    (278, 'LLTC', 'Linear Technology Corp.', 'Information Technology', 'Semiconductors', 'Milpitas', ' California', 791907),
    (279, 'LLY', 'Lilly (Eli) & Co.', 'Health Care', 'Pharmaceuticals', 'Indianapolis', ' Indiana', 59478),
    (280, 'LMT', 'Lockheed Martin Corp.', 'Industrials', 'Aerospace & Defense', 'Bethesda', ' Maryland', 936468),
    (281, 'LNC', 'Lincoln National', 'Financials', 'Multi-line Insurance', 'Radnor', ' Pennsylvania', 59558),
    (282, 'LNT', 'Alliant Energy Corp', 'Utilities', 'Electric Utilities', 'Madison', ' Wisconsin', 352541),
    (283, 'LOW', 'Lowe''s Cos.', 'Consumer Discretionary', 'Home Improvement Retail', 'Mooresville', ' North Carolina', 60667),
    (284, 'LRCX', 'Lam Research', 'Information Technology', 'Semiconductor Equipment', 'Fremont', ' California', 707549),
    (285, 'LUK', 'Leucadia National Corp.', 'Financials', 'Multi-Sector Holdings', 'New York', ' New York', 96223),
    (286, 'LUV', 'Southwest Airlines', 'Industrials', 'Airlines', 'Dallas', ' Texas', 92380),
    (287, 'LVLT', 'Level 3 Communications', 'Telecommunications Services', 'Alternative Carriers', 'Broomfield', ' Colorado', 794323),
    (288, 'LYB', 'LyondellBasell', 'Materials', 'Diversified Chemicals', 'Rotterdam', ' Netherlands', 1489393),
    (289, 'M', 'Macy''s Inc.', 'Consumer Discretionary', 'Department Stores', 'Cincinnati', ' Ohio', 794367),
    (290, 'MA', 'Mastercard Inc.', 'Information Technology', 'Internet Software & Services', 'Harrison', ' New York', 1141391),
    (291, 'MAA', 'Mid-America Apartments', 'Real Estate', 'Residential REITs', 'Memphis', ' Tennessee', 912595),
    (292, 'MAC', 'Macerich', 'Real Estate', 'Retail REITs', 'Santa Monica', ' California', 912242),
    (293, 'MAR', 'Marriott Int''l.', 'Consumer Discretionary', 'Hotels, Resorts & Cruise Lines', 'Bethesda', ' Maryland', 1048286),
    (294, 'MAS', 'Masco Corp.', 'Industrials', 'Building Products', 'Taylor', ' Michigan', 62996),
    (295, 'MAT', 'Mattel Inc.', 'Consumer Discretionary', 'Leisure Products', 'El Segundo', ' California', 63276),
    (296, 'MCD', 'McDonald''s Corp.', 'Consumer Discretionary', 'Restaurants', 'Oak Brook', ' Illinois', 63908),
    (297, 'MCHP', 'Microchip Technology', 'Information Technology', 'Semiconductors', 'Chandler', ' Arizona', 827054),
    (298, 'MCK', 'McKesson Corp.', 'Health Care', 'Health Care Distributors', 'San Francisco', ' California', 927653),
    (299, 'MCO', 'Moody''s Corp', 'Financials', 'Diversified Financial Services', 'New York', ' New York', 1059556),
    (300, 'MDLZ', 'Mondelez International', 'Consumer Staples', 'Packaged Foods & Meats', 'Northfield', ' Illinois', 1103982),
    (301, 'MDT', 'Medtronic plc', 'Health Care', 'Health Care Equipment', 'Dublin', ' Ireland', 64670),
    (302, 'MET', 'MetLife Inc.', 'Financials', 'Life & Health Insurance', 'New York', ' New York', 1099219),
    (303, 'MHK', 'Mohawk Industries', 'Consumer Discretionary', 'Home Furnishings', 'Amsterdam', ' New York', 851968),
    (304, 'MJN', 'Mead Johnson', 'Consumer Staples', 'Packaged Foods & Meats', 'Glenview', ' Illinois', 1452575),
    (305, 'MKC', 'McCormick & Co.', 'Consumer Staples', 'Packaged Foods & Meats', 'Sparks', ' Maryland', 63754),
    (306, 'MLM', 'Martin Marietta Materials', 'Materials', 'Construction Materials', 'Raleigh', ' North Carolina', 916076),
    (307, 'MMC', 'Marsh & McLennan', 'Financials', 'Insurance Brokers', 'New York', ' New York', 62709),
    (308, 'MMM', '3M Company', 'Industrials', 'Industrial Conglomerates', 'St. Paul', ' Minnesota', 66740),
    (309, 'MNK', 'Mallinckrodt Plc', 'Health Care', 'Pharmaceuticals', 'Dublin', ' Ireland', 1567892),
    (310, 'MNST', 'Monster Beverage', 'Consumer Staples', 'Soft Drinks', 'Corona', ' California', 865752),
    (311, 'MO', 'Altria Group Inc', 'Consumer Staples', 'Tobacco', 'Richmond', ' Virginia', 764180),
    (312, 'MON', 'Monsanto Co.', 'Materials', 'Fertilizers & Agricultural Chemicals', 'Creve Coeur', ' Missouri', 1110783),
    (313, 'MOS', 'The Mosaic Company', 'Materials', 'Fertilizers & Agricultural Chemicals', 'Plymouth', ' Minnesota', 1285785),
    (314, 'MPC', 'Marathon Petroleum', 'Energy', 'Oil & Gas Refining & Marketing & Transportation', 'Findlay', ' Ohio', 1510295),
    (315, 'MRK', 'Merck & Co.', 'Health Care', 'Pharmaceuticals', 'Whitehouse Station', ' New Jersey', 310158),
    (316, 'MRO', 'Marathon Oil Corp.', 'Energy', 'Oil & Gas Exploration & Production', 'Houston', ' Texas', 101778),
    (317, 'MS', 'Morgan Stanley', 'Financials', 'Investment Banking & Brokerage', 'New York', ' New York', 895421),
    (318, 'MSFT', 'Microsoft Corp.', 'Information Technology', 'Systems Software', 'Redmond', ' Washington', 789019),
    (319, 'MSI', 'Motorola Solutions Inc.', 'Information Technology', 'Telecommunications Equipment', 'Schaumburg', ' Illinois', 68505),
    (320, 'MTB', 'M&T Bank Corp.', 'Financials', 'Banks', 'Buffalo', ' New York', 36270),
    (321, 'MTD', 'Mettler Toledo', 'Health Care', 'Life Sciences Tools & Services', 'Columbus', ' Ohio', 1037646),
    (322, 'MU', 'Micron Technology', 'Information Technology', 'Semiconductors', 'Boise', ' Idaho', 723125),
    (323, 'MUR', 'Murphy Oil', 'Energy', 'Integrated Oil & Gas', 'El Dorado', ' Arkansas', 717423),
    (324, 'MYL', 'Mylan N.V.', 'Health Care', 'Pharmaceuticals', 'Amsterdam', ' Netherlands', 69499),
    (325, 'NAVI', 'Navient', 'Financials', 'Consumer Finance', 'Newark', ' Delaware', 1593538),
    (326, 'NBL', 'Noble Energy Inc', 'Energy', 'Oil & Gas Exploration & Production', 'Houston', ' Texas', 72207),
    (327, 'NDAQ', 'NASDAQ OMX Group', 'Financials', 'Diversified Financial Services', 'New York', ' New York', 1120193),
    (328, 'NEE', 'NextEra Energy', 'Utilities', 'MultiUtilities', 'Juno Beach', ' Florida', 753308),
    (329, 'NEM', 'Newmont Mining Corp. (Hldg. Co.)', 'Materials', 'Gold', 'Denver', ' Colorado', 1164727),
    (330, 'NFLX', 'Netflix Inc.', 'Information Technology', 'Internet Software & Services', 'Los Gatos', ' California', 1065280),
    (331, 'NFX', 'Newfield Exploration Co', 'Energy', 'Oil & Gas Exploration & Production', 'Houston', ' Texas', 912750),
    (332, 'NI', 'NiSource Inc.', 'Utilities', 'MultiUtilities', 'Merrillville', ' Indiana', 1111711),
    (333, 'NKE', 'Nike', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'Washington County', ' Oregon', 320187),
    (334, 'NLSN', 'Nielsen Holdings', 'Industrials', 'Research & Consulting Services', 'New York', ' New York', 1492633),
    (335, 'NOC', 'Northrop Grumman Corp.', 'Industrials', 'Aerospace & Defense', 'West Falls Church', ' Virginia', 1133421),
    (336, 'NOV', 'National Oilwell Varco Inc.', 'Energy', 'Oil & Gas Equipment & Services', 'Houston', ' Texas', 1021860),
    (337, 'NRG', 'NRG Energy', 'Utilities', 'Independent Power Producers & Energy Traders', 'Princeton', ' New Jersey', 1013871),
    (338, 'NSC', 'Norfolk Southern Corp.', 'Industrials', 'Railroads', 'Norfolk', ' Virginia', 702165),
    (339, 'NTAP', 'NetApp', 'Information Technology', 'Internet Software & Services', 'Sunnyvale', ' California', 1002047),
    (340, 'NTRS', 'Northern Trust Corp.', 'Financials', 'Asset Management & Custody Banks', 'Chicago', ' Illinois', 73124),
    (341, 'NUE', 'Nucor Corp.', 'Materials', 'Steel', 'Charlotte', ' North Carolina', 73309),
    (342, 'NVDA', 'Nvidia Corporation', 'Information Technology', 'Semiconductors', 'Santa Clara', ' California', 1045810),
    (343, 'NWL', 'Newell Brands', 'Consumer Discretionary', 'Housewares & Specialties', 'Sandy Springs', ' Georgia', 814453),
    (344, 'NWS', 'News Corp. Class B', 'Consumer Discretionary', 'Publishing', 'New York', ' New York', 1564708),
    (345, 'NWSA', 'News Corp. Class A', 'Consumer Discretionary', 'Publishing', 'New York', ' New York', 1564708),
    (346, 'O', 'Realty Income Corporation', 'Real Estate', 'Retail REITs', 'San Diego', ' California', 726728),
    (347, 'OKE', 'ONEOK', 'Energy', 'Oil & Gas Exploration & Production', 'Tulsa', ' Oklahoma', 1039684),
    (348, 'OMC', 'Omnicom Group', 'Consumer Discretionary', 'Advertising', 'New York', ' New York', 29989),
    (349, 'ORCL', 'Oracle Corp.', 'Information Technology', 'Application Software', 'Redwood Shores', ' California', 1341439),
    (350, 'ORLY', 'O''Reilly Automotive', 'Consumer Discretionary', 'Specialty Stores', 'Springfield', ' Missouri', 898173),
    (351, 'OXY', 'Occidental Petroleum', 'Energy', 'Oil & Gas Exploration & Production', 'Los Angeles', ' California', 797468),
    (352, 'PAYX', 'Paychex Inc.', 'Information Technology', 'Internet Software & Services', 'Penfield', ' New York', 723531),
    (353, 'PBCT', 'People''s United Financial', 'Financials', 'Thrifts & Mortgage Finance', 'Bridgeport', ' Connecticut', 1378946),
    (354, 'PBI', 'Pitney-Bowes', 'Industrials', 'Technology, Hardware, Software and Supplies', 'Stamford', ' Connecticut', 78814),
    (355, 'PCAR', 'PACCAR Inc.', 'Industrials', 'Construction & Farm Machinery & Heavy Trucks', 'Bellevue', ' Washington', 75362),
    (356, 'PCG', 'PG&E Corp.', 'Utilities', 'MultiUtilities', 'San Francisco', ' California', 1004980),
    (357, 'PCLN', 'Priceline.com Inc', 'Consumer Discretionary', 'Internet & Direct Marketing Retail', 'Norwalk', ' Connecticut', 1075531),
    (358, 'PDCO', 'Patterson Companies', 'Health Care', 'Health Care Supplies', 'St. Paul', ' Minnesota', 891024),
    (359, 'PEG', 'Public Serv. Enterprise Inc.', 'Utilities', 'Electric Utilities', 'Newark', ' New Jersey', 788784),
    (360, 'PEP', 'PepsiCo Inc.', 'Consumer Staples', 'Soft Drinks', 'Purchase', ' New York', 77476),
    (361, 'PFE', 'Pfizer Inc.', 'Health Care', 'Pharmaceuticals', 'New York', ' New York', 78003),
    (362, 'PFG', 'Principal Financial Group', 'Financials', 'Diversified Financial Services', 'Des Moines', ' Iowa', 1126328),
    (363, 'PG', 'Procter & Gamble', 'Consumer Staples', 'Personal Products', 'Cincinnati', ' Ohio', 80424),
    (364, 'PGR', 'Progressive Corp.', 'Financials', 'Property & Casualty Insurance', 'Mayfield Village', ' Ohio', 80661),
    (365, 'PH', 'Parker-Hannifin', 'Industrials', 'Industrial Conglomerates', 'Cleveland', ' Ohio', 76334),
    (366, 'PHM', 'Pulte Homes Inc.', 'Consumer Discretionary', 'Homebuilding', 'Atlanta', ' Georgia', 822416),
    (367, 'PKI', 'PerkinElmer', 'Health Care', 'Health Care Equipment', 'Waltham', ' Massachusetts', 31791),
    (368, 'PLD', 'Prologis', 'Real Estate', 'REITs', 'San Francisco', ' California', 1045609),
    (369, 'PM', 'Philip Morris International', 'Consumer Staples', 'Tobacco', 'New York', ' New York', 1413329),
    (370, 'PNC', 'PNC Financial Services', 'Financials', 'Banks', 'Pittsburgh', ' Pennsylvania', 713676),
    (371, 'PNR', 'Pentair Ltd.', 'Industrials', 'Industrial Machinery', 'Worsley', ' UK', 77360),
    (372, 'PNW', 'Pinnacle West Capital', 'Utilities', 'MultiUtilities', 'Phoenix', ' Arizona', 764622),
    (373, 'PPG', 'PPG Industries', 'Materials', 'Diversified Chemicals', 'Pittsburgh', ' Pennsylvania', 79879),
    (374, 'PPL', 'PPL Corp.', 'Utilities', 'Electric Utilities', 'Allentown', ' Pennsylvania', 922224),
    (375, 'PRGO', 'Perrigo', 'Health Care', 'Pharmaceuticals', 'Dublin', ' Ireland', 1585364),
    (376, 'PRU', 'Prudential Financial', 'Financials', 'Diversified Financial Services', 'Newark', ' New Jersey', 1137774),
    (377, 'PSA', 'Public Storage', 'Real Estate', 'REITs', 'Glendale', ' California', 1393311),
    (378, 'PSX', 'Phillips 66', 'Energy', 'Oil & Gas Refining & Marketing & Transportation', 'Houston', ' Texas', 1534701),
    (379, 'PVH', 'PVH Corp.', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'New York', ' New York', 78239),
    (380, 'PWR', 'Quanta Services Inc.', 'Industrials', 'Industrial Conglomerates', 'Houston', ' Texas', 1050915),
    (381, 'PX', 'Praxair Inc.', 'Materials', 'Industrial Gases', 'Danbury', ' Connecticut', 884905),
    (382, 'PXD', 'Pioneer Natural Resources', 'Energy', 'Oil & Gas Exploration & Production', 'Irving', ' Texas', 1038357),
    (383, 'PYPL', 'PayPal', 'Information Technology', 'Data Processing & Outsourced Services', 'San Jose', ' California', 1633917),
    (384, 'QCOM', 'QUALCOMM Inc.', 'Information Technology', 'Semiconductors', 'San Diego', ' California', 804328),
    (385, 'QRVO', 'Qorvo', 'Information Technology', 'Semiconductors', 'Greensboro', ' North Carolina', 1604778),
    (386, 'R', 'Ryder System', 'Industrials', 'Industrial Conglomerates', 'Miami', ' Florida', 85961),
    (387, 'RAI', 'Reynolds American Inc.', 'Consumer Staples', 'Tobacco', 'Winston-Salem', ' North Carolina', 1275283),
    (388, 'RCL', 'Royal Caribbean Cruises Ltd', 'Consumer Discretionary', 'Hotels, Resorts & Cruise Lines', 'Miami', ' Florida', 884887),
    (389, 'REGN', 'Regeneron', 'Health Care', 'Biotechnology', 'Tarrytown', ' New York', 872589),
    (390, 'RF', 'Regions Financial Corp.', 'Financials', 'Diversified Financial Services', 'Birmingham', ' Alabama', 1281761),
    (391, 'RHI', 'Robert Half International', 'Industrials', 'Human Resource & Employment Services', 'Menlo Park', ' California', 315213),
    (392, 'RHT', 'Red Hat Inc.', 'Information Technology', 'Systems Software', 'Raleigh', ' North Carolina', 1087423),
    (393, 'RIG', 'Transocean', 'Energy', 'Oil & Gas Drilling', 'Vernier', ' Switzerland', 1451505),
    (394, 'RL', 'Polo Ralph Lauren Corp.', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'New York', ' New York', 1037038),
    (395, 'ROK', 'Rockwell Automation Inc.', 'Industrials', 'Industrial Conglomerates', 'Milwaukee', ' Wisconsin', 1024478),
    (396, 'ROP', 'Roper Industries', 'Industrials', 'Industrial Conglomerates', 'Sarasota', ' Florida', 882835),
    (397, 'ROST', 'Ross Stores', 'Consumer Discretionary', 'Apparel Retail', 'Pleasanton', ' California', 745732),
    (398, 'RRC', 'Range Resources Corp.', 'Energy', 'Oil & Gas Exploration & Production', 'Fort Worth', ' Texas', 315852),
    (399, 'RSG', 'Republic Services Inc', 'Industrials', 'Industrial Conglomerates', 'Phoenix', ' Arizona', 1060391),
    (400, 'RTN', 'Raytheon Co.', 'Industrials', 'Aerospace & Defense', 'Waltham', ' Massachusetts', 1047122),
    (401, 'SBUX', 'Starbucks Corp.', 'Consumer Discretionary', 'Restaurants', 'Seattle', ' Washington', 829224),
    (402, 'SCG', 'SCANA Corp', 'Utilities', 'MultiUtilities', 'Cayce', ' South Carolina', 754737),
    (403, 'SCHW', 'Charles Schwab Corporation', 'Financials', 'Investment Banking & Brokerage', 'San Francisco', ' California', 316709),
    (404, 'SE', 'Spectra Energy Corp.', 'Energy', 'Oil & Gas Refining & Marketing & Transportation', 'Houston', ' Texas', 1373835),
    (405, 'SEE', 'Sealed Air', 'Materials', 'Paper Packaging', 'Elmwood Park', ' New Jersey', 1012100),
    (406, 'SHW', 'Sherwin-Williams', 'Materials', 'Specialty Chemicals', 'Cleveland', ' Ohio', 89800),
    (407, 'SIG', 'Signet Jewelers', 'Consumer Discretionary', 'Specialty Stores', 'Hamilton', ' Bermuda', 832988),
    (408, 'SJM', 'JM Smucker', 'Consumer Staples', 'Packaged Foods & Meats', 'Orrville', ' Ohio', 91419),
    (409, 'SLB', 'Schlumberger Ltd.', 'Energy', 'Oil & Gas Equipment & Services', 'Cura', ' Kingdom of the Netherlands', 87347),
    (410, 'SLG', 'SL Green Realty', 'Real Estate', 'Office REITs', 'New York', ' New York', 1040971),
    (411, 'SNA', 'Snap-On Inc.', 'Consumer Discretionary', 'Household Appliances', 'Kenosha', ' Wisconsin', 91440),
    (412, 'SNI', 'Scripps Networks Interactive Inc.', 'Consumer Discretionary', 'Broadcasting & Cable TV', 'Cincinnati', ' Ohio', 1430602),
    (413, 'SO', 'Southern Co.', 'Utilities', 'Electric Utilities', 'Atlanta', ' Georgia', 92122),
    (414, 'SPG', 'Simon Property Group Inc', 'Real Estate', 'REITs', 'Indianapolis', ' Indiana', 1063761),
    (415, 'SPGI', 'S&P Global, Inc.', 'Financials', 'Diversified Financial Services', 'New York', ' New York', 64040),
    (416, 'SPLS', 'Staples Inc.', 'Consumer Discretionary', 'Specialty Stores', 'Framingham', ' Massachusetts', 791519),
    (417, 'SRCL', 'Stericycle Inc', 'Industrials', 'Industrial Conglomerates', 'Lake Forest', ' Illinois', 861878),
    (418, 'SRE', 'Sempra Energy', 'Utilities', 'MultiUtilities', 'San Diego', ' California', 1032208),
    (419, 'STI', 'SunTrust Banks', 'Financials', 'Banks', 'Atlanta', ' Georgia', 750556),
    (420, 'STT', 'State Street Corp.', 'Financials', 'Diversified Financial Services', 'Boston', ' Massachusetts', 93751),
    (421, 'STX', 'Seagate Technology', 'Information Technology', 'Computer Storage & Peripherals', 'Dublin', ' Ireland', 1137789),
    (422, 'STZ', 'Constellation Brands', 'Consumer Staples', 'Distillers & Vintners', 'Victor', ' New York', 16918),
    (423, 'SWK', 'Stanley Black & Decker', 'Consumer Discretionary', 'Household Appliances', 'New Britain', ' Connecticut', 93556),
    (424, 'SWKS', 'Skyworks Solutions', 'Information Technology', 'Semiconductors', 'Woburn', ' Massachusetts', 4127),
    (425, 'SWN', 'Southwestern Energy', 'Energy', 'Oil & Gas Exploration & Production', 'Houston', ' Texas', 7332),
    (426, 'SYF', 'Synchrony Financial', 'Financials', 'Consumer Finance', 'Stamford', ' Connecticut', 1601712),
    (427, 'SYK', 'Stryker Corp.', 'Health Care', 'Health Care Equipment', 'Kalamazoo', ' Michigan', 310764),
    (428, 'SYMC', 'Symantec Corp.', 'Information Technology', 'Application Software', 'Mountain View', ' California', 849399),
    (429, 'SYY', 'Sysco Corp.', 'Consumer Staples', 'Food Distributors', 'Houston', ' Texas', 96021),
    (430, 'T', 'AT&T Inc', 'Telecommunications Services', 'Integrated Telecommunications Services', 'Dallas', ' Texas', 732717),
    (431, 'TAP', 'Molson Coors Brewing Company', 'Consumer Staples', 'Brewers', 'Denver', ' Colorado', 24545),
    (432, 'TDC', 'Teradata Corp.', 'Information Technology', 'Application Software', 'Miamisburg', ' Ohio', 816761),
    (433, 'TDG', 'TransDigm Group', 'Industrials', 'Aerospace & Defense', 'Cleveland', ' Ohio', 1260221),
    (434, 'TEL', 'TE Connectivity Ltd.', 'Information Technology', 'Electronic Manufacturing Services', 'Schaffhausen', ' Switzerland', 1385157),
    (435, 'TGNA', 'Tegna, Inc.', 'Consumer Discretionary', 'Publishing', 'McLean', ' Virginia', 39899),
    (436, 'TGT', 'Target Corp.', 'Consumer Discretionary', 'General Merchandise Stores', 'Minneapolis', ' Minnesota', 27419),
    (437, 'TIF', 'Tiffany & Co.', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'New York', ' New York', 98246),
    (438, 'TJX', 'TJX Companies Inc.', 'Consumer Discretionary', 'Apparel Retail', 'Framingham', ' Massachusetts', 109198),
    (439, 'TMK', 'Torchmark Corp.', 'Financials', 'Life & Health Insurance', 'McKinney', ' Texas', 320335),
    (440, 'TMO', 'Thermo Fisher Scientific', 'Health Care', 'Health Care Equipment', 'Waltham', ' Massachusetts', 97745),
    (441, 'TRIP', 'TripAdvisor', 'Consumer Discretionary', 'Internet & Direct Marketing Retail', 'Newton', ' Massachusetts', 1526520),
    (442, 'TROW', 'T. Rowe Price Group', 'Financials', 'Diversified Financial Services', 'Baltimore', ' Maryland', 1113169),
    (443, 'TRV', 'The Travelers Companies Inc.', 'Financials', 'Property & Casualty Insurance', 'New York', ' New York', 86312),
    (444, 'TSCO', 'Tractor Supply Company', 'Consumer Discretionary', 'Specialty Retail', 'Brentwood', ' Tennessee', 916365),
    (445, 'TSN', 'Tyson Foods', 'Consumer Staples', 'Packaged Foods & Meats', 'Springdale', ' Arkansas', 100493),
    (446, 'TSO', 'Tesoro Petroleum Co.', 'Energy', 'Oil & Gas Refining & Marketing & Transportation', 'San Antonio', ' Texas', 50104),
    (447, 'TSS', 'Total System Services', 'Information Technology', 'Internet Software & Services', 'Columbus', ' Georgia', 721683),
    (448, 'TWX', 'Time Warner Inc.', 'Consumer Discretionary', 'Broadcasting & Cable TV', 'New York', ' New York', 1105705),
    (449, 'TXN', 'Texas Instruments', 'Information Technology', 'Semiconductors', 'Dallas', ' Texas', 97476),
    (450, 'TXT', 'Textron Inc.', 'Industrials', 'Industrial Conglomerates', 'Providence', ' Rhode Island', 217346),
    (451, 'UA', 'Under Armour', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'Baltimore', ' Maryland', 1336917),
    (452, 'UAA', 'Under Armour', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'Baltimore', ' Maryland', 1336917),
    (453, 'UAL', 'United Continental Holdings', 'Industrials', 'Airlines', 'Chicago', ' Illinois', 100517),
    (454, 'UDR', 'UDR Inc', 'Real Estate', 'Residential REITs', 'Highlands Ranch', ' Colorado', 74208),
    (455, 'UHS', 'Universal Health Services, Inc.', 'Health Care', 'Health Care Facilities', 'King of Prussia', ' Pennsylvania', 352915),
    (456, 'ULTA', 'Ulta Salon Cosmetics & Fragrance Inc', 'Consumer Discretionary', 'Specialty Stores', 'Bolingbrook', ' Illinois', 1403568),
    (457, 'UNH', 'United Health Group Inc.', 'Health Care', 'Managed Health Care', 'Minnetonka', ' Minnesota', 731766),
    (458, 'UNM', 'Unum Group', 'Financials', 'Diversified Financial Services', 'Chattanooga', ' Tennessee', 5513),
    (459, 'UNP', 'Union Pacific', 'Industrials', 'Railroads', 'Omaha', ' Nebraska', 100885),
    (460, 'UPS', 'United Parcel Service', 'Industrials', 'Air Freight & Logistics', 'Atlanta', ' Georgia', 1090727),
    (461, 'URBN', 'Urban Outfitters', 'Consumer Discretionary', 'Apparel Retail', 'Philadelphia', ' Pennsylvania', 912615),
    (462, 'URI', 'United Rentals, Inc.', 'Industrials', 'Trading Companies & Distributors', 'Stamford', ' Connecticut', 1067701),
    (463, 'USB', 'U.S. Bancorp', 'Financials', 'Banks', 'Minneapolis', ' Minnesota', 36104),
    (464, 'UTX', 'United Technologies', 'Industrials', 'Industrial Conglomerates', 'Hartford', ' Connecticut', 101829),
    (465, 'V', 'Visa Inc.', 'Information Technology', 'Internet Software & Services', 'San Francisco', ' California', 1403161),
    (466, 'VAR', 'Varian Medical Systems', 'Health Care', 'Health Care Equipment', 'Palo Alto', ' California', 203527),
    (467, 'VFC', 'V.F. Corp.', 'Consumer Discretionary', 'Apparel, Accessories & Luxury Goods', 'Greensboro', ' North Carolina', 103379),
    (468, 'VIAB', 'Viacom Inc.', 'Consumer Discretionary', 'Broadcasting & Cable TV', 'New York', ' New York', 1339947),
    (469, 'VLO', 'Valero Energy', 'Energy', 'Oil & Gas Refining & Marketing & Transportation', 'San Antonio', ' Texas', 1035002),
    (470, 'VMC', 'Vulcan Materials', 'Materials', 'Construction Materials', 'Birmingham', ' Alabama', 1396009),
    (471, 'VNO', 'Vornado Realty Trust', 'Real Estate', 'REITs', 'New York', ' New York', 899689),
    (472, 'VRSK', 'Verisk Analytics', 'Industrials', 'Research & Consulting Services', 'Jersey City', ' New Jersey', 1442145),
    (473, 'VRSN', 'Verisign Inc.', 'Information Technology', 'Internet Software & Services', 'Dulles', ' Virginia', 1014473),
    (474, 'VRTX', 'Vertex Pharmaceuticals Inc', 'Health Care', 'Biotechnology', 'Cambridge', ' Massachusetts', 875320),
    (475, 'VTR', 'Ventas Inc', 'Real Estate', 'REITs', 'Chicago', ' Illinois', 740260),
    (476, 'VZ', 'Verizon Communications', 'Telecommunications Services', 'Integrated Telecommunications Services', 'New York', ' New York', 732712),
    (477, 'WAT', 'Waters Corporation', 'Health Care', 'Health Care Distributors', 'Milford', ' Massachusetts', 1000697),
    (478, 'WBA', 'Walgreens Boots Alliance', 'Consumer Staples', 'Drug Retail', 'Deerfield', ' Illinois', 1618921),
    (479, 'WDC', 'Western Digital', 'Information Technology', 'Computer Storage & Peripherals', 'Irvine', ' California', 106040),
    (480, 'WEC', 'Wec Energy Group Inc', 'Utilities', 'Electric Utilities', 'Milwaukee', ' Wisconsin', 783325),
    (481, 'WFC', 'Wells Fargo', 'Financials', 'Banks', 'San Francisco', ' California', 72971),
    (482, 'WFM', 'Whole Foods Market', 'Consumer Staples', 'Food Retail', 'Austin', ' Texas', 865436),
    (483, 'WHR', 'Whirlpool Corp.', 'Consumer Discretionary', 'Household Appliances', 'Benton Harbor', ' Michigan', 106640),
    (484, 'WLTW', 'Willis Towers Watson', 'Financials', 'Insurance Brokers', 'London', ' United Kingdom', 1140536),
    (485, 'WM', 'Waste Management Inc.', 'Industrials', 'Environmental Services', 'Houston', ' Texas', 823768),
    (486, 'WMB', 'Williams Cos.', 'Energy', 'Oil & Gas Exploration & Production', 'Tulsa', ' Oklahoma', 107263),
    (487, 'WMT', 'Wal-Mart Stores', 'Consumer Staples', 'Hypermarkets & Super Centers', 'Bentonville', ' Arkansas', 104169),
    (488, 'WRK', 'WestRock Company', 'Materials', 'Paper Packaging', 'Richmond', ' Virginia', 1636023),
    (489, 'WU', 'Western Union Co', 'Information Technology', 'Internet Software & Services', 'Englewood', ' Colorado', 1365135),
    (490, 'WY', 'Weyerhaeuser Corp.', 'Real Estate', 'REITs', 'Federal Way', ' Washington', 106535),
    (491, 'WYN', 'Wyndham Worldwide', 'Consumer Discretionary', 'Hotels, Resorts & Cruise Lines', 'Parsippany', ' New Jersey', 1361658),
    (492, 'WYNN', 'Wynn Resorts Ltd', 'Consumer Discretionary', 'Casinos & Gaming', 'Las Vegas', ' Nevada', 1174922),
    (493, 'XEC', 'Cimarex Energy', 'Energy', 'Oil & Gas Exploration & Production', 'Denver', ' Colorado', 1168054),
    (494, 'XEL', 'Xcel Energy Inc', 'Utilities', 'MultiUtilities', 'Minneapolis', ' Minnesota', 72903),
    (495, 'XL', 'XL Capital', 'Financials', 'Property & Casualty Insurance', 'Hamilton', ' Bermuda', 875159),
    (496, 'XLNX', 'Xilinx Inc', 'Information Technology', 'Semiconductors', 'San Jose', ' California', 743988),
    (497, 'XOM', 'Exxon Mobil Corp.', 'Energy', 'Integrated Oil & Gas', 'Irving', ' Texas', 34088),
    (498, 'XRAY', 'Dentsply Sirona', 'Health Care', 'Health Care Supplies', 'York', ' Pennsylvania', 818479),
    (499, 'XRX', 'Xerox Corp.', 'Information Technology', 'IT Consulting & Other Services', 'Norwalk', ' Connecticut', 108772),
    (500, 'XYL', 'Xylem Inc.', 'Industrials', 'Industrial Conglomerates', 'White Plains', ' New York', 1524472),
    (501, 'YHOO', 'Yahoo Inc.', 'Information Technology', 'Internet Software & Services', 'Sunnyvale', ' California', 1011006),
    (502, 'YUM', 'Yum! Brands Inc', 'Consumer Discretionary', 'Restaurants', 'Louisville', ' Kentucky', 1041061),
    (503, 'ZBH', 'Zimmer Biomet Holdings', 'Health Care', 'Health Care Equipment', 'Warsaw', ' Indiana', 1136869),
    (504, 'ZION', 'Zions Bancorp', 'Financials', 'Regional Banks', 'Salt Lake City', ' Utah', 109380),
    (505, 'ZTS', 'Zoetis', 'Health Care', 'Pharmaceuticals', 'Florham Park', ' New Jersey', 1555280)

SET IDENTITY_INSERT companies OFF;